services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    ports:
      - 5432:5432
    restart: always
    volumes:
      - 'fstpg:/var/lib/postgresql/data'
    # command: ["postgres", "-c", "log_statement=all"]

volumes:
  fstpg:
